import type {
  ChildProfile,
  HealthRecord,
  VaccineRecord,
  MedicineRecord,
  SymptomRecord,
  VisitRecord,
  Caregiver,
  Reminder,
} from '../types';
import { calculateBMI } from '../utils/formatters';
import { addDays, addMonths, formatDate } from '../utils/dateUtils';
import { VACCINE_SCHEDULE } from '../utils/constants';

export const mockChildren: ChildProfile[] = [
  {
    id: 'child-1',
    name: '小明',
    gender: 'male',
    birthday: '2021-03-15',
    avatar: '😎',
    age: 5,
    bloodType: 'A+',
    allergies: ['花生', '海鲜'],
    medicalHistory: ['2022年曾患肺炎住院'],
    birthWeight: 3.45,
    birthHeight: 50.5,
    headCircumference: 34.5,
    note: '活泼好动，喜欢运动，饮食规律',
    createdAt: '2021-03-15T08:00:00.000Z',
    updatedAt: '2026-06-01T10:00:00.000Z',
  },
  {
    id: 'child-2',
    name: '小红',
    gender: 'female',
    birthday: '2023-08-20',
    avatar: '🌸',
    age: 2,
    bloodType: 'O+',
    allergies: ['牛奶'],
    medicalHistory: [],
    birthWeight: 3.2,
    birthHeight: 49.8,
    headCircumference: 33.8,
    note: '文静乖巧，喜欢画画，睡眠质量好',
    createdAt: '2023-08-20T14:30:00.000Z',
    updatedAt: '2026-06-01T10:00:00.000Z',
  },
];

function generateHealthRecordsForChild1(): HealthRecord[] {
  const childId = 'child-1';
  const records: HealthRecord[] = [];
  const data = [
    { date: '2021-06-15', height: 63.2, weight: 6.8, headCircumference: 41.0, sleepHours: 15.5, waterIntake: 500, temperature: 36.7 },
    { date: '2021-09-15', height: 70.1, weight: 8.5, headCircumference: 44.2, sleepHours: 14.0, waterIntake: 650, temperature: 36.8 },
    { date: '2021-12-15', height: 76.3, weight: 10.2, headCircumference: 46.5, sleepHours: 13.5, waterIntake: 800, temperature: 36.6 },
    { date: '2022-03-15', height: 82.5, weight: 11.5, headCircumference: 47.8, sleepHours: 13.0, waterIntake: 900, temperature: 36.7 },
    { date: '2022-06-15', height: 88.2, weight: 12.8, headCircumference: 48.6, sleepHours: 12.5, waterIntake: 1000, temperature: 36.5 },
    { date: '2022-09-15', height: 93.5, weight: 14.0, sleepHours: 12.0, waterIntake: 1100, temperature: 36.8 },
    { date: '2022-12-15', height: 97.8, weight: 15.2, sleepHours: 11.5, waterIntake: 1150, temperature: 36.7 },
    { date: '2023-03-15', height: 101.5, weight: 16.3, sleepHours: 11.5, waterIntake: 1200, temperature: 36.6 },
    { date: '2023-06-15', height: 105.2, weight: 17.5, sleepHours: 11.0, waterIntake: 1250, temperature: 36.7 },
    { date: '2023-09-15', height: 109.0, weight: 18.8, sleepHours: 11.0, waterIntake: 1300, temperature: 36.8 },
    { date: '2023-12-15', height: 112.3, weight: 20.0, sleepHours: 10.5, waterIntake: 1350, temperature: 36.6 },
    { date: '2024-03-15', height: 116.0, weight: 21.5, sleepHours: 10.5, waterIntake: 1400, temperature: 36.7 },
    { date: '2024-09-15', height: 122.5, weight: 24.0, sleepHours: 10.0, waterIntake: 1500, temperature: 36.8 },
    { date: '2025-03-15', height: 128.2, weight: 26.5, sleepHours: 10.0, waterIntake: 1600, temperature: 36.7 },
    { date: '2025-09-15', height: 133.8, weight: 29.0, sleepHours: 9.5, waterIntake: 1700, temperature: 36.6 },
    { date: '2026-03-15', height: 139.0, weight: 32.0, sleepHours: 9.5, waterIntake: 1800, temperature: 36.7 },
    { date: '2026-06-01', height: 141.2, weight: 33.5, sleepHours: 9.0, waterIntake: 1850, temperature: 36.8 },
  ];

  data.forEach((item, index) => {
    const bmi = calculateBMI(item.height, item.weight);
    records.push({
      id: `hr-c1-${index + 1}`,
      childId,
      date: item.date,
      height: item.height,
      weight: item.weight,
      headCircumference: item.headCircumference,
      sleepHours: item.sleepHours,
      waterIntake: item.waterIntake,
      temperature: item.temperature,
      bmi: bmi > 0 ? bmi : undefined,
      note: index === 3 ? '生长发育良好，营养均衡' : index === 8 ? '春季生长加速期' : undefined,
      createdAt: `${item.date}T09:00:00.000Z`,
    });
  });

  return records;
}

function generateHealthRecordsForChild2(): HealthRecord[] {
  const childId = 'child-2';
  const records: HealthRecord[] = [];
  const data = [
    { date: '2023-11-20', height: 62.5, weight: 6.5, headCircumference: 40.5, sleepHours: 15.0, waterIntake: 480, temperature: 36.6 },
    { date: '2024-02-20', height: 68.8, weight: 8.2, headCircumference: 43.8, sleepHours: 14.5, waterIntake: 600, temperature: 36.7 },
    { date: '2024-05-20', height: 74.2, weight: 9.5, headCircumference: 45.8, sleepHours: 14.0, waterIntake: 720, temperature: 36.5 },
    { date: '2024-08-20', height: 79.5, weight: 10.8, headCircumference: 46.8, sleepHours: 13.5, waterIntake: 800, temperature: 36.8 },
    { date: '2024-11-20', height: 84.0, weight: 12.0, headCircumference: 47.5, sleepHours: 13.0, waterIntake: 880, temperature: 36.6 },
    { date: '2025-02-20', height: 88.2, weight: 13.2, sleepHours: 12.5, waterIntake: 950, temperature: 36.7 },
    { date: '2025-05-20', height: 92.5, weight: 14.3, sleepHours: 12.5, waterIntake: 1000, temperature: 36.5 },
    { date: '2025-08-20', height: 96.8, weight: 15.5, sleepHours: 12.0, waterIntake: 1050, temperature: 36.7 },
    { date: '2025-11-20', height: 100.5, weight: 16.5, sleepHours: 11.5, waterIntake: 1100, temperature: 36.6 },
    { date: '2026-02-20', height: 103.8, weight: 17.5, sleepHours: 11.5, waterIntake: 1150, temperature: 36.8 },
    { date: '2026-04-20', height: 106.0, weight: 18.2, sleepHours: 11.0, waterIntake: 1200, temperature: 36.7 },
    { date: '2026-05-20', height: 107.5, weight: 18.8, sleepHours: 11.0, waterIntake: 1250, temperature: 36.5 },
    { date: '2026-05-28', height: undefined, weight: undefined, sleepHours: 10.5, waterIntake: 1180, temperature: 37.5 },
    { date: '2026-05-30', height: undefined, weight: undefined, sleepHours: 11.5, waterIntake: 1300, temperature: 36.8 },
    { date: '2026-06-01', height: 108.2, weight: 19.0, sleepHours: 11.0, waterIntake: 1280, temperature: 36.7 },
    { date: '2026-06-05', height: undefined, weight: undefined, sleepHours: 10.5, waterIntake: 1200, temperature: 36.6 },
  ];

  data.forEach((item, index) => {
    const bmi = item.height && item.weight ? calculateBMI(item.height, item.weight) : 0;
    records.push({
      id: `hr-c2-${index + 1}`,
      childId,
      date: item.date,
      height: item.height,
      weight: item.weight,
      headCircumference: item.headCircumference,
      sleepHours: item.sleepHours,
      waterIntake: item.waterIntake,
      temperature: item.temperature,
      bmi: bmi > 0 ? bmi : undefined,
      note: index === 12 ? '轻微感冒，多饮水' : undefined,
      createdAt: `${item.date}T09:00:00.000Z`,
    });
  });

  return records;
}

export const mockHealthRecords: HealthRecord[] = [
  ...generateHealthRecordsForChild1(),
  ...generateHealthRecordsForChild2(),
];

function generateVaccineRecords(birthday: string, childId: string): VaccineRecord[] {
  const records: VaccineRecord[] = [];
  const birthDate = new Date(birthday);
  const today = new Date();

  VACCINE_SCHEDULE.forEach((vaccine, index) => {
    const scheduledDate = addMonths(birthDate, vaccine.ageMonthsMin);
    const scheduledDateStr = formatDate(scheduledDate);
    const isPast = scheduledDate.getTime() < today.getTime();
    const isOverdue = isPast && (today.getTime() - scheduledDate.getTime()) > 30 * 24 * 60 * 60 * 1000;
    const isContraindicated = vaccine.code === 'MCV1' && childId === 'child-2';

    let status: 'completed' | 'pending' | 'overdue' | 'contraindicated' = 'pending';
    let actualDate: string | undefined;

    if (isContraindicated) {
      status = 'contraindicated';
    } else if (isPast) {
      if (isOverdue && Math.random() > 0.6) {
        status = 'overdue';
      } else {
        status = 'completed';
        actualDate = formatDate(addDays(scheduledDate, Math.floor(Math.random() * 14)));
      }
    }

    records.push({
      id: `vr-${childId}-${index + 1}`,
      childId,
      vaccineCode: vaccine.code,
      vaccineName: vaccine.name,
      scheduledAge: vaccine.scheduledAge,
      scheduledDate: scheduledDateStr,
      actualDate,
      status,
      batchNumber: status === 'completed' ? `B${vaccine.code}20${Math.floor(Math.random() * 9000 + 1000)}` : undefined,
      manufacturer: status === 'completed' ? ['国药集团', '科兴', '长春长生', '武汉生物'][Math.floor(Math.random() * 4)] : undefined,
      site: status === 'completed' ? ['左上臂', '右上臂', '左大腿', '右大腿'][Math.floor(Math.random() * 4)] : undefined,
      caregiver: status === 'completed' ? ['张护士', '李护士', '王医生'][Math.floor(Math.random() * 3)] : undefined,
      adverseReaction: status === 'completed' && Math.random() > 0.8 ? '轻微发热，1天后恢复' : undefined,
      note: isContraindicated ? '鸡蛋过敏，暂缓接种' : undefined,
      nextDoseDate: vaccine.code === 'DTaP1' ? formatDate(addMonths(birthDate, 4)) : undefined,
    });
  });

  return records;
}

export const mockVaccineRecords: VaccineRecord[] = [
  ...generateVaccineRecords('2021-03-15', 'child-1'),
  ...generateVaccineRecords('2023-08-20', 'child-2'),
];

export const mockMedicineRecords: MedicineRecord[] = [
  {
    id: 'med-1',
    childId: 'child-1',
    medicineName: '布洛芬混悬液',
    dosage: '5ml/次',
    frequency: '每6小时1次',
    startDate: '2025-10-15',
    endDate: '2025-10-18',
    reason: '发热39度，退热',
    prescribedBy: '儿科 王医生',
    sideEffects: '无明显不良反应',
    status: 'completed',
    note: '体温超过38.5度时使用，饭后服用',
  },
  {
    id: 'med-2',
    childId: 'child-1',
    medicineName: '阿莫西林克拉维酸钾干混悬剂',
    dosage: '1袋/次',
    frequency: '每日2次',
    startDate: '2025-10-15',
    endDate: '2025-10-22',
    reason: '细菌感染，扁桃体炎',
    prescribedBy: '儿科 王医生',
    sideEffects: '轻微腹泻',
    status: 'completed',
    note: '早晚饭后服用，多饮水',
  },
  {
    id: 'med-3',
    childId: 'child-1',
    medicineName: '小儿氨酚黄那敏颗粒',
    dosage: '1袋/次',
    frequency: '每日3次',
    startDate: '2026-05-20',
    endDate: '2026-05-25',
    reason: '感冒症状：流鼻涕、咳嗽',
    prescribedBy: '诊所 李医生',
    status: 'completed',
    note: '症状减轻后可停药',
  },
  {
    id: 'med-4',
    childId: 'child-2',
    medicineName: '对乙酰氨基酚滴剂',
    dosage: '1.5ml/次',
    frequency: '每4-6小时1次',
    startDate: '2025-08-12',
    endDate: '2025-08-14',
    reason: '接种疫苗后发热',
    prescribedBy: '预防保健科',
    sideEffects: '无',
    status: 'completed',
    note: '仅在体温超过38.5度时使用',
  },
  {
    id: 'med-5',
    childId: 'child-2',
    medicineName: '氯雷他定糖浆',
    dosage: '5ml/次',
    frequency: '每日1次',
    startDate: '2026-04-10',
    reason: '过敏性鼻炎，季节性花粉过敏',
    prescribedBy: '耳鼻喉科 张医生',
    sideEffects: '轻微嗜睡',
    status: 'active',
    note: '睡前服用，外出戴口罩',
  },
  {
    id: 'med-6',
    childId: 'child-2',
    medicineName: '维生素D滴剂',
    dosage: '400IU/次',
    frequency: '每日1次',
    startDate: '2023-09-01',
    reason: '日常补充，促进钙吸收',
    prescribedBy: '儿保科',
    status: 'active',
    note: '可长期服用，冬季适当增加日照',
  },
];

export const mockSymptomRecords: SymptomRecord[] = [
  {
    id: 'sym-1',
    childId: 'child-1',
    type: 'fever',
    timestamp: Date.now() - 2 * 3600 * 1000,
    startTime: Date.now() - 2 * 3600 * 1000,
    active: true,
    resolved: false,
    fever: {
      temperature: 38.7,
      measureTime: new Date(Date.now() - 30 * 60 * 1000).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }),
      mentalState: 'normal',
      measures: '已服用布洛芬，温水擦浴降温',
    },
    note: '幼儿园回来后开始发热',
  },
  {
    id: 'sym-2',
    childId: 'child-2',
    type: 'cough',
    timestamp: Date.now() - 5 * 3600 * 1000,
    startTime: Date.now() - 8 * 3600 * 1000,
    active: true,
    resolved: false,
    cough: {
      frequency: 'frequent',
      sputum: 'white',
      worseAtNight: true,
      mentalState: 'good',
      measures: '多喝水，室内加湿，蜂蜜水润喉',
    },
    note: '夜间咳嗽加重影响睡眠',
  },
  {
    id: 'sym-3',
    childId: 'child-1',
    type: 'diarrhea',
    timestamp: Date.now() - 25 * 3600 * 1000,
    startTime: Date.now() - 28 * 3600 * 1000,
    active: false,
    resolved: true,
    diarrhea: {
      timesPerDay: 5,
      stoolType: 'watery',
      dehydrationRisk: 'mild',
      mentalState: 'normal',
      measures: '口服补液盐，益生菌，清淡饮食',
    },
    note: '饮食不当引起，次日好转',
  },
  {
    id: 'sym-4',
    childId: 'child-1',
    type: 'cough',
    timestamp: Date.now() - 3 * 24 * 3600 * 1000,
    startTime: Date.now() - 3 * 24 * 3600 * 1000,
    active: false,
    resolved: true,
    cough: {
      frequency: 'occasional',
      sputum: 'clear',
      worseAtNight: false,
      mentalState: 'good',
      measures: '多休息，多喝水',
    },
    note: '换季轻微感冒咳嗽',
  },
  {
    id: 'sym-5',
    childId: 'child-2',
    type: 'fever',
    timestamp: Date.now() - 6 * 24 * 3600 * 1000,
    startTime: Date.now() - 6 * 24 * 3600 * 1000,
    active: false,
    resolved: true,
    fever: {
      temperature: 39.2,
      measureTime: '02:30',
      mentalState: 'bad',
      measures: '退热栓，物理降温，就医',
    },
    note: '高烧39度以上，使用退热栓后降温',
  },
  {
    id: 'sym-6',
    childId: 'child-1',
    type: 'fever',
    timestamp: Date.now() - 1 * 24 * 3600 * 1000,
    startTime: Date.now() - 1 * 24 * 3600 * 1000,
    active: false,
    resolved: true,
    fever: {
      temperature: 37.8,
      measureTime: '18:45',
      mentalState: 'good',
      measures: '多喝水，物理降温',
    },
    note: '傍晚低热，夜间自行消退',
  },
  {
    id: 'sym-7',
    childId: 'child-1',
    type: 'cough',
    timestamp: Date.now() - 4 * 24 * 3600 * 1000,
    startTime: Date.now() - 4 * 24 * 3600 * 1000,
    active: false,
    resolved: true,
    cough: {
      frequency: 'occasional',
      sputum: 'none',
      worseAtNight: false,
      mentalState: 'good',
      measures: '注意保暖，多喝水',
    },
    note: '干咳，几天后自愈',
  },
  {
    id: 'sym-8',
    childId: 'child-2',
    type: 'diarrhea',
    timestamp: Date.now() - 2 * 24 * 3600 * 1000,
    startTime: Date.now() - 2 * 24 * 3600 * 1000,
    active: false,
    resolved: true,
    diarrhea: {
      timesPerDay: 3,
      stoolType: 'loose',
      dehydrationRisk: 'none',
      mentalState: 'good',
      measures: '清淡饮食，观察即可',
    },
    note: '轻微腹泻，当日恢复',
  },
];

export const mockVisitRecords: VisitRecord[] = [
  {
    id: 'visit-1',
    childId: 'child-1',
    visitDate: '2025-10-15',
    hospital: '儿童医院',
    department: '儿科',
    doctor: '王大明',
    symptoms: ['发热39度', '咽部红肿', '扁桃体化脓'],
    diagnosis: '急性化脓性扁桃体炎',
    prescriptions: [
      { name: '布洛芬混悬液', dosage: '5ml/次', frequency: '发热时服用' },
      { name: '阿莫西林克拉维酸钾', dosage: '1袋/次', frequency: '每日2次' },
      { name: '开喉剑喷雾剂', dosage: '适量', frequency: '每日3次' },
    ],
    testResults: ['血常规：白细胞升高，中性粒细胞比例增高', 'C反应蛋白：阳性'],
    advice: '多饮水，清淡饮食，注意休息，3天后复诊，体温持续高热及时就诊',
    nextVisitDate: '2025-10-22',
    cost: 368.5,
    note: '精神状态良好，遵医嘱服药',
    category: 'fever',
    date: '2025-10-15',
    expense: 368.5,
    chiefComplaint: '发热2天，最高39.5度，伴咽痛',
    images: ['grad1', 'grad2', 'grad3'],
  },
  {
    id: 'visit-2',
    childId: 'child-1',
    visitDate: '2025-10-22',
    hospital: '儿童医院',
    department: '儿科',
    doctor: '王大明',
    symptoms: ['症状明显好转，体温正常'],
    diagnosis: '扁桃体炎恢复期',
    testResults: ['血常规：恢复正常'],
    advice: '继续服药1天停药，加强营养，适当活动',
    cost: 56.0,
    note: '恢复良好',
    category: 'other',
    date: '2025-10-22',
    expense: 56.0,
    chiefComplaint: '扁桃体炎复诊',
  },
  {
    id: 'visit-3',
    childId: 'child-1',
    visitDate: '2026-04-16',
    hospital: '中心医院',
    department: '皮肤科',
    doctor: '李芳芳',
    symptoms: ['全身散在红色风团，瘙痒明显'],
    diagnosis: '急性荨麻疹',
    prescriptions: [
      { name: '氯雷他定片', dosage: '10mg/次', frequency: '每日1次' },
      { name: '炉甘石洗剂', dosage: '适量外涂', frequency: '瘙痒时使用' },
      { name: '维生素C片', dosage: '1片/次', frequency: '每日3次' },
    ],
    testResults: ['过敏原检测：花粉、尘螨阳性'],
    advice: '避免接触过敏原，外出戴口罩，注意环境卫生，定期晒被褥',
    cost: 425.0,
    note: '建议过敏季节提前预防用药',
    category: 'other',
    date: '2026-04-16',
    expense: 425.0,
    chiefComplaint: '皮疹瘙痒2天',
    images: ['grad4', 'grad5'],
  },
  {
    id: 'visit-4',
    childId: 'child-2',
    visitDate: '2026-04-08',
    hospital: '妇幼保健院',
    department: '耳鼻喉科',
    doctor: '张晓峰',
    symptoms: ['鼻塞、流涕、眼睛痒，春季发作'],
    diagnosis: '季节性过敏性鼻炎',
    prescriptions: [
      { name: '氯雷他定糖浆', dosage: '5ml/次', frequency: '每日1次，睡前' },
      { name: '糠酸莫米松鼻喷雾剂', dosage: '每侧鼻孔1揿', frequency: '每日1次' },
      { name: '生理海盐水鼻腔冲洗', dosage: '适量', frequency: '每日2次' },
    ],
    testResults: ['过敏原检测：树木花粉阳性'],
    advice: '花粉季节减少外出，外出佩戴护目镜和口罩，回家后及时清洗面部',
    nextVisitDate: '2026-06-10',
    cost: 312.0,
    note: '连续3年同季节发作，建议免疫治疗评估',
    category: 'cold',
    date: '2026-04-08',
    expense: 312.0,
    chiefComplaint: '鼻塞流涕打喷嚏1周',
    images: ['grad1', 'grad2', 'grad3', 'grad4'],
  },
  {
    id: 'visit-5',
    childId: 'child-2',
    visitDate: '2026-01-21',
    hospital: '第一人民医院',
    department: '儿科急诊',
    doctor: '赵敏',
    symptoms: ['频繁呕吐、水样便、轻度脱水'],
    diagnosis: '轮状病毒肠炎',
    prescriptions: [
      { name: '蒙脱石散', dosage: '1袋/次', frequency: '每日3次，空腹' },
      { name: '口服补液盐III', dosage: '按需服用', frequency: '少量多次' },
      { name: '益生菌', dosage: '1袋/次', frequency: '每日2次' },
    ],
    testResults: ['大便常规：轮状病毒抗原阳性', '电解质：轻度低钾'],
    advice: '少量多次补充口服补液盐，清淡饮食，注意手卫生，隔离防护',
    cost: 289.0,
    note: '精神好转，尿量恢复正常后复诊',
    category: 'other',
    date: '2026-01-21',
    expense: 289.0,
    chiefComplaint: '呕吐腹泻1天',
  },
  {
    id: 'visit-6',
    childId: 'child-2',
    visitDate: '2026-05-20',
    hospital: '妇幼保健院',
    department: '儿童保健科',
    doctor: '陈华',
    symptoms: ['常规体检'],
    diagnosis: '健康体检，生长发育良好',
    testResults: ['身高体重：中等水平', '视力：正常', '听力：正常', '血常规：未见异常'],
    advice: '均衡饮食，多户外活动，保证充足睡眠，定期体检',
    nextVisitDate: '2026-11-20',
    cost: 198.0,
    note: '建议开始学习刷牙，注意口腔卫生',
    category: 'checkup',
    date: '2026-05-20',
    expense: 198.0,
    chiefComplaint: '2岁半体检',
    images: ['grad2', 'grad4', 'grad5', 'grad1', 'grad3'],
  },
];

export const mockCaregivers: Caregiver[] = [
  {
    id: 'cg-1',
    name: '张伟',
    relation: 'father',
    phone: '13800138001',
    email: 'zhangwei@example.com',
    permission: 'admin',
    avatar: '👨',
    permissions: ['growth', 'vaccine', 'medicine', 'symptom', 'visit', 'family', 'export'],
    note: '主要照护人，负责日常管理',
    createdAt: '2021-03-15T00:00:00.000Z',
  },
  {
    id: 'cg-2',
    name: '李娜',
    relation: 'mother',
    phone: '13800138002',
    email: 'lina@example.com',
    permission: 'admin',
    avatar: '👩',
    permissions: ['growth', 'vaccine', 'medicine', 'symptom', 'visit', 'family', 'export'],
    note: '主要照护人，负责饮食和健康记录',
    createdAt: '2021-03-15T00:00:00.000Z',
  },
  {
    id: 'cg-3',
    name: '张爷爷',
    relation: 'grandfather',
    phone: '13900139003',
    permission: 'view',
    avatar: '👴',
    permissions: ['growth', 'vaccine', 'visit'],
    note: '周末帮忙照看',
    createdAt: '2021-04-01T00:00:00.000Z',
  },
  {
    id: 'cg-4',
    name: '王阿姨',
    relation: 'grandmother',
    phone: '13800138008',
    permission: 'edit',
    avatar: '👵',
    permissions: ['medicine', 'symptom', 'growth'],
    note: '日常帮忙接送孩子',
    createdAt: '2023-06-10T00:00:00.000Z',
  },
];

export const mockReminders: Reminder[] = [
  {
    id: 'rm-1',
    childId: 'child-1',
    title: '流脑A+C群多糖疫苗第2剂',
    type: 'vaccine',
    date: '2027-03-15',
    time: '09:00',
    frequency: 'once',
    status: 'active',
    note: '6岁接种，提前预约社区卫生服务中心',
    relatedRecordId: 'vr-child-1-21',
    createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    id: 'rm-2',
    childId: 'child-1',
    title: '白破疫苗',
    type: 'vaccine',
    date: '2027-03-15',
    time: '09:00',
    frequency: 'once',
    status: 'active',
    note: '6岁加强接种',
    relatedRecordId: 'vr-child-1-22',
    createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    id: 'rm-3',
    childId: 'child-2',
    title: '季节性流感疫苗',
    type: 'vaccine',
    date: '2026-10-15',
    time: '08:30',
    frequency: 'yearly',
    status: 'active',
    note: '秋季接种，预防冬季流感',
    createdAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'rm-4',
    childId: 'child-2',
    title: '服用氯雷他定糖浆',
    type: 'medicine',
    date: '2026-06-09',
    time: '21:00',
    frequency: 'daily',
    status: 'active',
    note: '睡前服用5ml',
    relatedRecordId: 'med-5',
    createdAt: '2026-04-10T00:00:00.000Z',
  },
  {
    id: 'rm-5',
    childId: 'child-2',
    title: '服用维生素D滴剂',
    type: 'medicine',
    date: '2026-06-09',
    time: '08:00',
    frequency: 'daily',
    status: 'active',
    note: '早餐后服用，400IU',
    relatedRecordId: 'med-6',
    createdAt: '2023-09-01T00:00:00.000Z',
  },
  {
    id: 'rm-6',
    childId: 'child-2',
    title: '耳鼻喉科复诊',
    type: 'visit',
    date: '2026-06-10',
    time: '14:30',
    frequency: 'once',
    status: 'active',
    note: '妇幼保健院耳鼻喉科，张医生',
    relatedRecordId: 'visit-4',
    createdAt: '2026-04-08T00:00:00.000Z',
  },
  {
    id: 'rm-7',
    childId: 'child-2',
    title: '半年度健康体检',
    type: 'measurement',
    date: '2026-11-20',
    time: '09:30',
    frequency: 'monthly',
    status: 'active',
    note: '儿童保健科体检，测量身高体重视力',
    relatedRecordId: 'visit-6',
    createdAt: '2026-05-20T00:00:00.000Z',
  },
  {
    id: 'rm-8',
    childId: 'child-1',
    title: '每日身高体重记录',
    type: 'measurement',
    date: '2026-06-09',
    time: '07:30',
    frequency: 'weekly',
    status: 'active',
    note: '每周日早晨空腹测量并记录',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'rm-9',
    childId: 'child-1',
    title: '饮水提醒',
    type: 'other',
    date: '2026-06-09',
    time: '10:00',
    frequency: 'daily',
    status: 'active',
    note: '课间补充水分，目标每日1800ml',
    createdAt: '2026-03-01T00:00:00.000Z',
  },
];
