import type { VaccineDefinition } from '../types';

export const VACCINE_SCHEDULE: VaccineDefinition[] = [
  {
    code: 'BCG',
    name: '卡介苗',
    fullName: '卡介苗 (BCG)',
    scheduledAge: '出生时',
    ageMonthsMin: 0,
    ageMonthsMax: 1,
    doses: 1,
    preventDiseases: ['结核病'],
    route: '皮内注射',
    category: 'free',
  },
  {
    code: 'HepB1',
    name: '乙肝疫苗第1剂',
    fullName: '乙型肝炎疫苗 (第1剂)',
    scheduledAge: '出生时',
    ageMonthsMin: 0,
    ageMonthsMax: 1,
    doses: 1,
    preventDiseases: ['乙型肝炎'],
    route: '肌内注射',
    category: 'free',
  },
  {
    code: 'HepB2',
    name: '乙肝疫苗第2剂',
    fullName: '乙型肝炎疫苗 (第2剂)',
    scheduledAge: '1月龄',
    ageMonthsMin: 1,
    ageMonthsMax: 2,
    doses: 1,
    preventDiseases: ['乙型肝炎'],
    route: '肌内注射',
    category: 'free',
  },
  {
    code: 'IPV1',
    name: '脊灰灭活疫苗第1剂',
    fullName: '脊髓灰质炎灭活疫苗 (第1剂)',
    scheduledAge: '2月龄',
    ageMonthsMin: 2,
    ageMonthsMax: 3,
    doses: 1,
    preventDiseases: ['脊髓灰质炎'],
    route: '肌内注射',
    category: 'free',
  },
  {
    code: 'DTaP1',
    name: '百白破疫苗第1剂',
    fullName: '百白破联合疫苗 (第1剂)',
    scheduledAge: '3月龄',
    ageMonthsMin: 3,
    ageMonthsMax: 4,
    doses: 1,
    preventDiseases: ['百日咳', '白喉', '破伤风'],
    route: '肌内注射',
    category: 'free',
  },
  {
    code: 'IPV2',
    name: '脊灰灭活疫苗第2剂',
    fullName: '脊髓灰质炎灭活疫苗 (第2剂)',
    scheduledAge: '3月龄',
    ageMonthsMin: 3,
    ageMonthsMax: 4,
    doses: 1,
    preventDiseases: ['脊髓灰质炎'],
    route: '口服',
    category: 'free',
  },
  {
    code: 'DTaP2',
    name: '百白破疫苗第2剂',
    fullName: '百白破联合疫苗 (第2剂)',
    scheduledAge: '4月龄',
    ageMonthsMin: 4,
    ageMonthsMax: 5,
    doses: 1,
    preventDiseases: ['百日咳', '白喉', '破伤风'],
    route: '肌内注射',
    category: 'free',
  },
  {
    code: 'bOPV1',
    name: '脊灰减毒活疫苗第1剂',
    fullName: '二价脊灰减毒活疫苗 (第1剂)',
    scheduledAge: '4月龄',
    ageMonthsMin: 4,
    ageMonthsMax: 5,
    doses: 1,
    preventDiseases: ['脊髓灰质炎'],
    route: '口服',
    category: 'free',
  },
  {
    code: 'DTaP3',
    name: '百白破疫苗第3剂',
    fullName: '百白破联合疫苗 (第3剂)',
    scheduledAge: '5月龄',
    ageMonthsMin: 5,
    ageMonthsMax: 6,
    doses: 1,
    preventDiseases: ['百日咳', '白喉', '破伤风'],
    route: '肌内注射',
    category: 'free',
  },
  {
    code: 'HepB3',
    name: '乙肝疫苗第3剂',
    fullName: '乙型肝炎疫苗 (第3剂)',
    scheduledAge: '6月龄',
    ageMonthsMin: 6,
    ageMonthsMax: 8,
    doses: 1,
    preventDiseases: ['乙型肝炎'],
    route: '肌内注射',
    category: 'free',
  },
  {
    code: 'bOPV2',
    name: '脊灰减毒活疫苗第2剂',
    fullName: '二价脊灰减毒活疫苗 (第2剂)',
    scheduledAge: '6月龄',
    ageMonthsMin: 6,
    ageMonthsMax: 8,
    doses: 1,
    preventDiseases: ['脊髓灰质炎'],
    route: '口服',
    category: 'free',
  },
  {
    code: 'MCV1',
    name: '麻腮风疫苗第1剂',
    fullName: '麻腮风联合疫苗 (第1剂)',
    scheduledAge: '8月龄',
    ageMonthsMin: 8,
    ageMonthsMax: 9,
    doses: 1,
    preventDiseases: ['麻疹', '流行性腮腺炎', '风疹'],
    route: '皮下注射',
    category: 'free',
  },
  {
    code: 'JE-L1',
    name: '乙脑减毒活疫苗第1剂',
    fullName: '乙型脑炎减毒活疫苗 (第1剂)',
    scheduledAge: '8月龄',
    ageMonthsMin: 8,
    ageMonthsMax: 12,
    doses: 1,
    preventDiseases: ['流行性乙型脑炎'],
    route: '皮下注射',
    category: 'free',
  },
  {
    code: 'MCV2',
    name: '麻腮风疫苗第2剂',
    fullName: '麻腮风联合疫苗 (第2剂)',
    scheduledAge: '18月龄',
    ageMonthsMin: 18,
    ageMonthsMax: 24,
    doses: 1,
    preventDiseases: ['麻疹', '流行性腮腺炎', '风疹'],
    route: '皮下注射',
    category: 'free',
  },
  {
    code: 'DTaP4',
    name: '百白破疫苗第4剂',
    fullName: '百白破联合疫苗 (第4剂)',
    scheduledAge: '18月龄',
    ageMonthsMin: 18,
    ageMonthsMax: 24,
    doses: 1,
    preventDiseases: ['百日咳', '白喉', '破伤风'],
    route: '肌内注射',
    category: 'free',
  },
  {
    code: 'HepA-L',
    name: '甲肝减毒活疫苗',
    fullName: '甲型肝炎减毒活疫苗',
    scheduledAge: '18月龄',
    ageMonthsMin: 18,
    ageMonthsMax: 30,
    doses: 1,
    preventDiseases: ['甲型肝炎'],
    route: '皮下注射',
    category: 'free',
  },
  {
    code: 'JE-L2',
    name: '乙脑减毒活疫苗第2剂',
    fullName: '乙型脑炎减毒活疫苗 (第2剂)',
    scheduledAge: '2岁',
    ageMonthsMin: 24,
    ageMonthsMax: 36,
    doses: 1,
    preventDiseases: ['流行性乙型脑炎'],
    route: '皮下注射',
    category: 'free',
  },
  {
    code: 'MenA1',
    name: '流脑A群多糖疫苗第1剂',
    fullName: 'A群脑膜炎球菌多糖疫苗 (第1剂)',
    scheduledAge: '6月龄',
    ageMonthsMin: 6,
    ageMonthsMax: 18,
    doses: 1,
    preventDiseases: ['A群流行性脑脊髓膜炎'],
    route: '皮下注射',
    category: 'free',
  },
  {
    code: 'MenA2',
    name: '流脑A群多糖疫苗第2剂',
    fullName: 'A群脑膜炎球菌多糖疫苗 (第2剂)',
    scheduledAge: '9月龄',
    ageMonthsMin: 9,
    ageMonthsMax: 24,
    doses: 1,
    preventDiseases: ['A群流行性脑脊髓膜炎'],
    route: '皮下注射',
    category: 'free',
  },
  {
    code: 'MenAC1',
    name: '流脑A+C群多糖疫苗第1剂',
    fullName: 'A群C群脑膜炎球菌多糖疫苗 (第1剂)',
    scheduledAge: '3岁',
    ageMonthsMin: 36,
    ageMonthsMax: 48,
    doses: 1,
    preventDiseases: ['A群C群流行性脑脊髓膜炎'],
    route: '皮下注射',
    category: 'free',
  },
  {
    code: 'MenAC2',
    name: '流脑A+C群多糖疫苗第2剂',
    fullName: 'A群C群脑膜炎球菌多糖疫苗 (第2剂)',
    scheduledAge: '6岁',
    ageMonthsMin: 72,
    ageMonthsMax: 84,
    doses: 1,
    preventDiseases: ['A群C群流行性脑脊髓膜炎'],
    route: '皮下注射',
    category: 'free',
  },
  {
    code: 'DT',
    name: '白破疫苗',
    fullName: '白喉破伤风联合疫苗',
    scheduledAge: '6岁',
    ageMonthsMin: 72,
    ageMonthsMax: 84,
    doses: 1,
    preventDiseases: ['白喉', '破伤风'],
    route: '肌内注射',
    category: 'free',
  },
  {
    code: 'PPSV23',
    name: '肺炎球菌多糖疫苗',
    fullName: '23价肺炎球菌多糖疫苗',
    scheduledAge: '2岁以上',
    ageMonthsMin: 24,
    ageMonthsMax: 144,
    doses: 1,
    preventDiseases: ['肺炎球菌感染'],
    route: '肌内注射',
    category: 'paid',
    note: '自愿接种',
  },
  {
    code: 'Var',
    name: '水痘疫苗',
    fullName: '水痘减毒活疫苗',
    scheduledAge: '1岁/4岁',
    ageMonthsMin: 12,
    ageMonthsMax: 48,
    doses: 2,
    preventDiseases: ['水痘'],
    route: '皮下注射',
    category: 'paid',
    note: '自愿接种',
  },
  {
    code: 'Flu',
    name: '流感疫苗',
    fullName: '季节性流感疫苗',
    scheduledAge: '6月龄以上',
    ageMonthsMin: 6,
    ageMonthsMax: 144,
    doses: 1,
    preventDiseases: ['流行性感冒'],
    route: '肌内注射',
    category: 'paid',
    note: '每年接种',
  },
  {
    code: 'RV',
    name: '轮状病毒疫苗',
    fullName: '轮状病毒疫苗',
    scheduledAge: '2月龄-3岁',
    ageMonthsMin: 2,
    ageMonthsMax: 36,
    doses: 1,
    preventDiseases: ['轮状病毒肠炎'],
    route: '口服',
    category: 'paid',
    note: '每年接种',
  },
];

export const ALLERGIES_COMMON: string[] = [
  '牛奶',
  '鸡蛋',
  '花生',
  '坚果',
  '海鲜',
  '鱼类',
  '虾',
  '蟹',
  '贝类',
  '小麦',
  '大豆',
  '芒果',
  '菠萝',
  '猕猴桃',
  '草莓',
  '花粉',
  '尘螨',
  '动物毛发',
  '霉菌',
  '昆虫叮咬',
  '青霉素',
  '头孢类',
  '磺胺类',
  '阿司匹林',
  '防腐剂',
  '食品添加剂',
  '香精香料',
  '染料',
  '乳胶',
  '紫外线',
];

export const PERMISSIONS: { value: string; label: string; description: string }[] = [
  {
    value: 'admin',
    label: '管理员',
    description: '可查看、编辑、删除所有数据，管理照护人权限',
  },
  {
    value: 'edit',
    label: '编辑者',
    description: '可查看和编辑所有数据，但不可删除或管理权限',
  },
  {
    value: 'view',
    label: '查看者',
    description: '仅可查看数据，不可进行任何编辑操作',
  },
];

export const RELATIONS: { value: string; label: string; icon?: string }[] = [
  { value: 'father', label: '爸爸' },
  { value: 'mother', label: '妈妈' },
  { value: 'grandfather', label: '爷爷' },
  { value: 'grandmother', label: '奶奶' },
  { value: 'maternal_grandfather', label: '外公' },
  { value: 'maternal_grandmother', label: '外婆' },
  { value: 'uncle', label: '叔叔' },
  { value: 'aunt', label: '阿姨' },
  { value: 'brother', label: '哥哥' },
  { value: 'sister', label: '姐姐' },
  { value: 'nanny', label: '保姆' },
  { value: 'other', label: '其他' },
];

export const BLOOD_TYPES: string[] = ['A', 'B', 'AB', 'O', 'A+', 'B+', 'AB+', 'O+', 'A-', 'B-', 'AB-', 'O-'];

export const VACCINE_STATUS_LABELS: Record<string, string> = {
  completed: '已接种',
  pending: '待接种',
  overdue: '已逾期',
  contraindicated: '禁忌症',
};

export const VACCINE_STATUS_COLORS: Record<string, string> = {
  completed: '#22c55e',
  pending: '#3b82f6',
  overdue: '#ef4444',
  contraindicated: '#6b7280',
};

export const SYMPTOM_SEVERITY_LABELS: Record<string, string> = {
  mild: '轻微',
  moderate: '中等',
  severe: '严重',
};

export const SYMPTOM_SEVERITY_COLORS: Record<string, string> = {
  mild: '#22c55e',
  moderate: '#f59e0b',
  severe: '#ef4444',
};

export const REMINDER_TYPE_LABELS: Record<string, string> = {
  vaccine: '疫苗接种',
  medicine: '用药提醒',
  visit: '就诊复查',
  measurement: '健康测量',
  other: '其他提醒',
};

export const REMINDER_TYPE_COLORS: Record<string, string> = {
  vaccine: '#8b5cf6',
  medicine: '#06b6d4',
  visit: '#f97316',
  measurement: '#22c55e',
  other: '#6b7280',
};

export const COMMON_SYMPTOMS: string[] = [
  '发烧',
  '咳嗽',
  '流鼻涕',
  '打喷嚏',
  '鼻塞',
  '喉咙痛',
  '头痛',
  '腹痛',
  '腹泻',
  '便秘',
  '呕吐',
  '恶心',
  '食欲不振',
  '皮疹',
  '瘙痒',
  '眼睛红肿',
  '耳朵痛',
  '流口水',
  '打鼾',
  '呼吸困难',
  '疲劳',
  '烦躁',
  '失眠',
  '出汗',
  '颤抖',
  '关节痛',
  '肌肉痛',
  '口臭',
  '口腔溃疡',
  '牙龈出血',
];

export const MEDICINE_STATUS_LABELS: Record<string, string> = {
  active: '用药中',
  completed: '已完成',
  stopped: '已停药',
};

export const MEDICINE_STATUS_COLORS: Record<string, string> = {
  active: '#22c55e',
  completed: '#3b82f6',
  stopped: '#6b7280',
};

export const DEPARTMENTS: string[] = [
  '儿科',
  '儿内科',
  '儿外科',
  '皮肤科',
  '眼科',
  '耳鼻喉科',
  '口腔科',
  '骨科',
  '神经科',
  '消化科',
  '呼吸科',
  '心血管科',
  '内分泌科',
  '泌尿科',
  '精神心理科',
  '康复科',
  '中医科',
  '急诊科',
  '预防保健科',
];

export const HOSPITALS: string[] = [
  '儿童医院',
  '第一人民医院',
  '中心医院',
  '妇幼保健院',
  '协和医院',
  '同济医院',
  '中山医院',
  '人民医院',
  '医大附属一院',
  '医大附属二院',
];
